// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"database/sql"
)

type Article struct {
	ID          int32
	Nid         string
	RssID       string
	Url         string
	Title       string
	Summary     sql.NullString
	Content     sql.NullString
	Authors     sql.NullString
	Media       sql.NullString
	PublishedAt sql.NullTime
	FeedID      sql.NullInt32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Feed struct {
	ID        int32
	Nid       string
	Url       string
	Title     string
	Summary   sql.NullString
	Authors   sql.NullString
	Image     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        int32
	Username  string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserFeed struct {
	UserID int32
	FeedID int32
}
