// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Article struct {
	ID        int64
	ArticleID string
	Url       string
	Title     string
	Summary   sql.NullString
	Content   sql.NullString
	Authors   sql.NullString
	Media     sql.NullString
	FeedID    string
}

type Feed struct {
	ID      int64
	FeedID  string
	Url     string
	Title   string
	Summary sql.NullString
	Authors sql.NullString
	Image   sql.NullString
}

type User struct {
	ID       int64
	Username string
	Password string
}
